### ISSUE TITLE
ActiveRecord::StatementInvalid in Admin/users#show  

### ISSUE THREAD

**Issue by hging** [qiushibaike/moumentei#1]
Mysql2::Error: Unknown column 'articles.article_id' in 'where clause': SELECT sum(`articles`.score) AS sum_score FROM `articles` WHERE (`articles`.`article_id` IN (NULL)) 
Extracted source (around line #33):

30:   <li>Articles: <%= @user.articles.count  %></li>
31:   <li>Public: <%= @user.articles.public.count %></li>
32:   <li>Comments: <%= @user.comments.count %></li>
33:   <li>Total Articles Score <%= @user.total_articles_score %></li>
34:   <li>Total Comments Score <%= @user.total_comments_score %></li>
35:   <li>Total articles comments <%= @user.total_articles_comments_count %></li>
36:   <li>average Articles Score <%= @user.average_articles_score %></li>
RAILS_ROOT: C:/Users/GONG/Documents/GitHub/moumentei

Application Trace | Framework Trace | Full Trace
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract_adapter.rb:227:in `log'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-mysql2-adapter-0.0.3/lib/active_record/connection_adapters/mysql2_adapter.rb:265:in`execute'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-mysql2-adapter-0.0.3/lib/active_record/connection_adapters/mysql2_adapter.rb:615:in `select'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in`select_all_without_query_cache'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/query_cache.rb:60:in `select_all'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/query_cache.rb:81:in`cache_sql'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/query_cache.rb:60:in `select_all'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in`select_one'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/database_statements.rb:19:in `select_value'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/calculations.rb:237:in`execute_simple_calculation'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/calculations.rb:134:in `calculate'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/calculations.rb:130:in`catch'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/calculations.rb:130:in `calculate'
c:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/calculations.rb:84:in`sum'
C:/Users/GONG/Documents/GitHub/moumentei/app/models/user/charm_aspect.rb:12:in `total_articles_score'
C:/Users/GONG/Documents/GitHub/moumentei/app/views/admin/users/show.erb:33:in`_run_erb_app47views47admin47users47show46erb'

**Comment by hging** [comment]
fixed
